name: Workflow test on latest Ubuntu and Python 3.10

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  sponge-test:        
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Check Python version
      run: |
        which python3
        python3 --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        
    - name: Set up the submodule
      run: |
        git submodule init
        git submodule update
      
    - name: Check the submodule
      run: |
        cd scripts
        cd lib
        cd ..
        cd ..
      
    - name: Check the symlink
      run: |
        cd lib
        cd ..

    # - name: Run the tests
    #   run: snakemake --cores=1 --configfile=tests/test_config.yaml