name: Workflow test on a combination of Python versions and OS

on:
  push:
    branches:
    - main
    - devel
  pull_request:
    branches:
    - main
    - devel

jobs:
  os-python-compatibility:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        python: [ '3.9', '3.10', '3.11' ]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Check Python version
      run: |
        which python3
        python3 --version

    - name: Install MacOS-specific hdf5 dependency
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install hdf5 c-blosc
        export HDF5_DIR=/opt/homebrew/Cellar/hdf5/
        export BLOSC_DIR=/opt/homebrew/Cellar/c-blosc/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
      
    - name: Set up the submodule
      run: |
        git submodule init
        git submodule update
        
    - name: Check the submodule
      run: |
        cd scripts
        cd lib
        cd ..
        cd ..
      
    - name: Check the symlink
      run: |
        cd lib
        cd ..

    # - name: Run the tests
    #   run: snakemake --cores=1 --configfile=tests/test_config.yaml
